### ISSUE TITLE
Differences from spf13/afero 

### ISSUE THREAD

**Issue by ghostsquad** [hack-pad/hackpadfs#12]
I'm curious what this brings to the table that https://github.com/spf13/afero does not have?

**Comment by JohnStarich** [comment]
Afero takes a holistic interface approach to file systems, for the most part. In other words, your own FS must implement all of the different file and filesystem operations in order to be used. HackpadFS gives you more flexibility by only requiring implementations use small, composable interfaces. The interop with `io/fs` is improved as a result.

It also lacked consistency in behavior and had a few game-breaking bugs when it was first pulled into Hackpad. I actually reached out with [bug fixes](https://github.com/spf13/afero/pulls?q=is%3Apr+author%3AJohnStarich+) and also [offered to improve things](https://github.com/spf13/afero/issues/253), though they had a different plan for the project. HackpadFS adds the shared test suite that was missing from afero.

**Comment by gedw99** [comment]
https://github.com/fclairamb/afero-s3 might be interesting you this project

It allows you to read and write to s3 from what i can see.
