### ISSUE TITLE
Request for a `sub` method that returns the original `FS`

### ISSUE THREAD

**Issue by ghostsquad** [hack-pad/hackpadfs#15]
```Go
// Sub implements hackpadfs.SubFS
func (fs *FS) Sub(dir string) (hackpadfs.FS, error) {
	if !hackpadfs.ValidPath(dir) {
		return nil, &hackpadfs.PathError{Op: "sub", Path: dir, Err: hackpadfs.ErrInvalid}
	}
	return &FS{
		root: path.Join(fs.root, dir),
	}, nil
}
```

I'd like to use `Sub` but get back the original `*FS`. So I think this would have to be a stand alone method, similar to `context.WithCancel`.

**Comment by JohnStarich** [comment]
Hey @ghostsquad, thanks for opening. Are you asking to mutate the current FS? This method `Sub()` implements SubFS from the standard library (copied into `hackpadfs`), so this one must return a new FS.

Could you provide more info on the problem you're facing? Maybe another solution is possible.

**Comment by ghostsquad** [comment]
Ya good question. I want to set the working directory of the FS essentially, so that future uses behave correctly when using relative paths.

**Comment by JohnStarich** [comment]
Ok got it. I think you're probably going to need something other than `Sub()` for handling working directories, since relative paths like `../x` wouldn't work on a standard Go FS.

I'll go ahead and close this one, since we're chatting about some possibilities of working directories over in https://github.com/hack-pad/hackpadfs/issues/14
